version: '3.9'

services:
  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6.0.4
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=posts
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: app
    ports:
      - "80:5000"
    env_file:
      - .env.development
    depends_on:
      - redis
      - mongo

volumes:
  redis-data:
  mongo-data: